### ISSUE TITLE
Plausible log in weekly/monthly email reports points to a HTTP 404 link 

### ISSUE THREAD

**Issue by wreidlinger** [plausible/hosting#132]
Hi there, I'm using the weekly/monthly email report feature and just noticed, that the Pausible logo in the email is not displayed.

![image](https://github.com/plausible/community-edition/assets/100240865/89d8d82c-bdda-48dc-839d-5dbaff017b05)

This is the link to the Plausible logo inside the HTML email:

`https://plausible.io/images/icon/plausible_logo-973ea42fac38d21a0a8cda9cfb9231c9.png?vsn=d `

The links gives me this:
![image](https://github.com/plausible/community-edition/assets/100240865/17eaab67-e0e6-4d2b-887b-3354b5f5b313)

Can I change the link for the Plausible logo somewhere of is this an issue which could be addressed by an update?

Many thanks!

**Comment by ruslandoga** [comment]
👋 @wreidlinger 

What Plausible version are you using? I think it should be fixed in v2.1.0 (image=ghcr.io/plausible/community-edition:v2.1.0)

**Comment by wreidlinger** [comment]
@ruslandoga thanks for your fast respond and sorry that I did not mention this info in my first post.
This is my `docker-compose.yml`, looks like I'm running **[v2.0.0](https://hub.docker.com/layers/plausible/analytics/latest/images/sha256-5bf2057948e1d5d12ef61f446c4945a336d3bcdf9b96293a1d6fc275f3c56eb5?context=explore)** with my config.

```
name: plausible
services:
# **************************************
# MAILSERVICE
# **************************************
  mail:
    image: sverzegnassi/smtp
    container_name: plausible_mail
    hostname: smtpmail
    #image: bytemark/smtp
    restart: always
    env_file:
      - plausible-conf.env

# **************************************
# DATABASE
# **************************************
  plausible_db:
    image: postgres:14-alpine
    container_name: plausible_db
    hostname: postgres
    restart: always
    volumes:
      - ./data/db-plausible:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

# **************************************
# EVENTS DATABASE
# **************************************
  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    container_name: plausible_events_db
    hostname: clickhouse
    restart: always
    volumes:
      - ./data/db-clickhouse:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

# **************************************
# PLAUSIBLE SERVICE
# **************************************
  plausible:
    image: plausible/analytics:latest
    container_name: plausible_plausible
    hostname: plausible
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db
      migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env
```

- `plausible-conf.env`

```
BASE_URL=https://plausible.mydomain.org
SECRET_KEY_BASE=HhmDhY1v****
TOTP_VAULT_KEY=***
DISABLE_REGISTRATION=true
DATABASE_URL=postgres://postgres:postgres@plausible_db:5432/plausible_db
CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible_events_db
# MAXMIND
MAXMIND_LICENSE_KEY=xVCXh4_***
MAXMIND_EDITION=GeoLite2-City
# MAIL
MAILER_EMAIL=plausible@mydomain.org
MAILER_NAME=plausible@mydomain.org
SMTP_HOST_ADDR=mail.mydomain.org
SMTP_HOST_PORT=465
SMTP_USER_NAME=plausible@mydomain.org
SMTP_USER_PWD=*****
SMTP_HOST_SSL_ENABLED=true
SMTP_RETRIES=2
```

Can you tell me if I can safely switch from `image: plausible/analytics:latest` to `image: ghcr.io/plausible/community-edition:latest` without breaking something? Looks like that I was building my stack with the wrong image...
Many thanks!
