### ISSUE TITLE
GMAIL: Messages missing a valid Message-ID

### ISSUE THREAD

**Issue by stoutZero** [plausible/hosting#149]
Someone help me please, it's been months without emails.  

And I have posted on the discussion board, a week without any response here:  
https://github.com/plausible/analytics/discussions/4421

Followed this gist: https://gist.github.com/ruslandoga/c94ce526231fb77930132aaeda3fc3c9.  

- Executed: `Application.get_env :plausible, Plausible.Mailer`
    - Result: `[adapter: Bamboo.Mua]`

- Sending email via

    ```elixir
    {:ok, _delivered_email} =
      Plausible.Mailer.deliver_now(
        Bamboo.Email.new_email(
          # pick one of your own mailboxes
          to: "<REDACTED>@gmail.com",
          from: PlausibleWeb.Email.mailer_email_from(),
          html_body: "test",
          text_body: "test",
        )
      )
    ```

  - Result:
    ```
    ** (MatchError) no match of right hand side value: {:error, %Mua.SMTPError{code: 550, lines: ["550-5.7.1 [51.79.207.19] Messages missing a valid Message-ID header are not\r\n", "550-5.7.1 accepted. For more information, go to\r\n", "550-5.7.1  https://support.google.com/mail/?p=RfcMessageNonCompliant and review\r\n", "550 5.7.1 RFC 5322 specifications. d9443c01a7336-200bbbcb176si51237545ad.431 - gsmtp\r\n"]}}
    (stdlib 5.2) erl_eval.erl:498: :erl_eval.expr/6
    iex:1: (file)
    ```

Shortened docker compose file:
<details>
  <summary>docker-compose.yml</summary>

  ```yml
  services:
    plausible:
      env_file:
        - plausible-conf.env
      image: 'ghcr.io/plausible/community-edition:v2.1.1'
      command: 'sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"'
      environment:
        DATABASE_URL: 'postgres://postgres:$SERVICE_PASSWORD_POSTGRES@plausible_db/plausible'
        BASE_URL: $SERVICE_FQDN_PLAUSIBLE
        SECRET_KEY_BASE: $SERVICE_BASE64_64_PLAUSIBLE
        TOTP_VAULT_KEY: $SERVICE_BASE64_TOTP
        COOLIFY_CONTAINER_NAME: plausible-ekoc4og
      depends_on:
        - plausible_db
        - plausible_events_db
      networks:
        ekoc4og: null
      labels:
        - coolify.managed=true
        - traefik.enable=true
      restart: unless-stopped
      container_name: plausible-ekoc4og
    plausible_db:
      image: 'postgres:14-alpine'
      volumes:
        - 'ekoc4og_db-data:/var/lib/postgresql/data'
      environment:
        POSTGRES_DB: plausible
        POSTGRES_PASSWORD: $SERVICE_PASSWORD_POSTGRES
        COOLIFY_CONTAINER_NAME: plausible_db-ekoc4og
      networks:
        ekoc4og: null
      labels:
        - coolify.managed=true
      restart: unless-stopped
      container_name: plausible_db-ekoc4og
    plausible_events_db:
      image: 'clickhouse/clickhouse-server:24.3.3.102-alpine'
      volumes:
        -
          type: volume
          source: ekoc4og_event-data
          target: /var/lib/clickhouse
        -
          type: bind
          source: ./clickhouse/clickhouse-config.xml
          target: /etc/clickhouse-server/config.d/logging.xml
          read_only: true
        -
          type: bind
          source: ./clickhouse/clickhouse-user-config.xml
          target: /etc/clickhouse-server/users.d/logging.xml
          read_only: true
      ulimits:
        nofile:
          soft: 262144
          hard: 262144
      networks:
        ekoc4og: null
      labels:
        - coolify.managed=true
      restart: unless-stopped
      container_name: plausible_events_db-ekoc4og
      environment:
        COOLIFY_CONTAINER_NAME: plausible_events_db-ekoc4og
  volumes:
    ekoc4og_db-data:
      name: ekoc4og_db-data
    ekoc4og_event-data:
      name: ekoc4og_event-data
  networks:
    ekoc4og:
      name: ekoc4og
      external: true
  configs: {  }
  secrets: {  }
  ```
</details>

Here is the content of the .env file I used:
<details>
  <summary>.env</summary>

  ```ini
  ADMIN_USER_EMAIL=<REDACTED>
  ADMIN_USER_NAME=<REDACTED>
  ADMIN_USER_PWD=<REDACTED>

  CRON_ENABLED=true

  DISABLE_REGISTRATION=invite_only

  MAXMIND_EDITION=GeoLite2-City
  MAXMIND_LICENSE_KEY=<REDACTED>

  SELFHOST=true

  SENTRY_DSN=<REDACTED>

  SERVICE_BASE64_TOTP=<REDACTED>
  SERVICE_FQDN_PLAUSIBLE=<REDACTED>
  SERVICE_PASSWORD_POSTGRES=<REDACTED>

  MAILER_ADAPTER=Bamboo.Mua
  MAILER_EMAIL=<REDACTED>
  MAILER_NAME=<REDACTED>
  SMTP_HOST=smtp.resend.com / smtp.gmail.com
  SMTP_HOST_SSL_ENABLED=true
  SMTP_PORT=587
  SMTP_PWD="<REDACTED>"
  SMTP_SECURITY=tls
  SMTP_USERNAME=resend / <REDACTED>@CUSTOM_DOMAIN
  ```
</details>

`binding()` on iex: `[]`  

Printing all env via ash on plausible container:

<details>
  <summary>export</summary>

  ```bash
  docker compose exec plausible ash
  /app $ export
  export ADMIN_USER_EMAIL='<REDACTED>'
  export ADMIN_USER_NAME='<REDACTED>'
  export ADMIN_USER_PWD='<REDACTED>'
  export BASE_URL='<REDACTED>'
  export BUILD_METADATA='{"tags":["ghcr.io/plausible/community-edition:v2.1.1",ghcr.io/plausible/community-edition:v2.1,ghcr.io/plausible/community-edition:v2,"ghcr.io/plausible/community-edition:latest"],"labels":{"org.opencontainers.image.created":"2024-06-06T09:38:56.952Z","org.opencontainers.image.description":"Simple, open source, lightweight (< 1 KB) and privacy-friendly web analytics alternative to Google Analytics.","org.opencontainers.image.licenses":"AGPL-3.0","org.opencontainers.image.revision":"b096057eef28f25f8223cb625dfd3303ffce521a","org.opencontainers.image.source":"https://github.com/plausible/analytics","org.opencontainers.image.title":"analytics","org.opencontainers.image.url":"https://github.com/plausible/analytics","org.opencontainers.image.version":"v2.1.1"},"annotations":["manifest:org.opencontainers.image.created=2024-06-06T09:38:56.952Z",manifest:org.opencontainers.image.description=Simple, open source, lightweight (< 1 KB) and privacy-friendly web analytics alternative to Google Analytics.,manifest:org.opencontainers.image.licenses=AGPL-3.0,manifest:org.opencontainers.image.revision=b096057eef28f25f8223cb625dfd3303ffce521a,manifest:org.opencontainers.image.source=https://github.com/plausible/analytics,manifest:org.opencontainers.image.title=analytics,manifest:org.opencontainers.image.url=https://github.com/plausible/analytics,"manifest:org.opencontainers.image.version=v2.1.1"]}'
  export COOLIFY_CONTAINER_NAME='plausible-ekoc4og'
  export CRON_ENABLED='true'
  export DATABASE_URL='<REDACTED>'
  export DISABLE_REGISTRATION='invite_only'
  export HOME='/home/plausible'
  export HOSTNAME='3998bc52315d'
  export LANG='C.UTF-8'
  export LISTEN_IP='0.0.0.0'
  export MAILER_ADAPTER='Bamboo.Mua'
  export MAILER_EMAIL='<REDACTED>'
  export MAILER_NAME='<REDACTED>'
  export MAXMIND_EDITION='GeoLite2-City'
  export MAXMIND_LICENSE_KEY='<REDACTED>'
  export MIX_ENV='ce'
  export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  export PWD='/app'
  export SECRET_KEY_BASE='<REDACTED>'
  export SELFHOST='true'
  export SENTRY_DSN='<REDACTED>'
  export SERVICE_BASE64_64_PLAUSIBLE='<REDACTED>'
  export SERVICE_BASE64_TOTP='<REDACTED>'
  export SERVICE_FQDN_PLAUSIBLE='<REDACTED>'
  export SERVICE_PASSWORD_POSTGRES='<REDACTED>'
  export SHLVL='1'
  export SMTP_HOST='smtp.resend.com'
  export SMTP_HOST_SSL_ENABLED='true'
  export SMTP_PORT='587'
  export SMTP_PWD='<REDACTED>'
  export SMTP_SECURITY='tls'
  export SMTP_USERNAME='resend'
  export TERM='xterm'
  export TOTP_VAULT_KEY='<REDACTED>'
  ```
</details>
