### ISSUE TITLE
Not starting completely... DB::exception

### ISSUE THREAD

**Issue by charleslcso** [plausible/hosting#190]
Hello,

First time install Plausible. Followed this guide. Created .env, and added "ports" to compose.yml. Nothing more.

compose.yml seem to be correct. I'm using port 8000:8000.

Then it hangs there, with an exception:

```
plausible_1            | ------------------------------------------------------------------------------
plausible_1            |     add-alias-column Done!
plausible_1            | 
plausible_1            | ------------------------------------------------------------------------------
plausible_1            |     update-location-data-table-comment Done!
plausible_1            | 
plausible_1            | ------------------------------------------------------------------------------




plausible_db_1         | 2024-12-02 13:48:35.972 UTC [52] LOG:  checkpoint starting: time
^CGracefully stopping... (press Ctrl+C again to force)
Stopping plausible-ce_plausible_1           ... done
Stopping plausible-ce_plausible_events_db_1 ... done
Stopping plausible-ce_plausible_db_1        ... done


root@plause:/opt/plausible-ce# docker-compose up
Starting plausible-ce_plausible_db_1        ... done
Starting plausible-ce_plausible_events_db_1 ... done
Starting plausible-ce_plausible_1           ... done
Attaching to plausible-ce_plausible_db_1, plausible-ce_plausible_events_db_1, plausible-ce_plausible_1
plausible_db_1         | 
plausible_db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
plausible_db_1         | 
plausible_db_1         | 2024-12-02 13:49:08.438 UTC [1] LOG:  starting PostgreSQL 16.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
plausible_db_1         | 2024-12-02 13:49:08.439 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
plausible_db_1         | 2024-12-02 13:49:08.439 UTC [1] LOG:  listening on IPv6 address "::", port 5432
plausible_db_1         | 2024-12-02 13:49:08.451 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
plausible_db_1         | 2024-12-02 13:49:08.457 UTC [28] LOG:  database system was shut down at 2024-12-02 13:49:03 UTC
plausible_db_1         | 2024-12-02 13:49:08.463 UTC [1] LOG:  database system is ready to accept connections
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | ClickHouse Database directory appears to contain a database; Skipping initialization
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
plausible_events_db_1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
plausible_events_db_1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
plausible_events_db_1  | Merging configuration file '/etc/clickhouse-server/config.d/ipv4-only.xml'.
plausible_events_db_1  | Merging configuration file '/etc/clickhouse-server/config.d/logs.xml'.
plausible_events_db_1  | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
plausible_events_db_1  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log

plausible_events_db_1  | 2024.12.02 13:49:08.905569 [ 1 ] {} <Warning> Context: Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.
plausible_events_db_1  | 2024.12.02 13:49:09.082894 [ 1 ] {} <Error> Application: Disabling cgroup memory observer because of an error during initialization: Code: 107. DB::Exception: Cannot find cgroups v1 or v2 current memory file. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
plausible_events_db_1  | 
plausible_events_db_1  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible_events_db_1  | 1. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x00000000076614c3
plausible_events_db_1  | 2. DB::CgroupsMemoryUsageObserver::CgroupsMemoryUsageObserver(std::chrono::duration<long long, std::ratio<1l, 1l>>) @ 0x000000000cce452e
plausible_events_db_1  | 3. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000cd562bd
plausible_events_db_1  | 4. Poco::Util::Application::run() @ 0x0000000014ca8606
plausible_events_db_1  | 5. DB::Server::run() @ 0x000000000cd46671
plausible_events_db_1  | 6. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000014cb14b9
plausible_events_db_1  | 7. mainEntryClickHouseServer(int, char**) @ 0x000000000cd4246a
plausible_events_db_1  | 8. main @ 0x0000000007651578
plausible_events_db_1  | 9. ? @ 0x00007f6920262083
plausible_events_db_1  | 10. _start @ 0x0000000005dee46e

plausible_events_db_1  |  (version 24.3.3.102 (official build))
plausible_1            | Loading plausible..
plausible_1            | Starting dependencies..
plausible_1            | Starting repos..
plausible_1            | Plausible.Repo database already exists
plausible_1            | Plausible.IngestRepo database already exists
plausible_1            | Creation of Db successful!
plausible_1            | Loading plausible..
plausible_1            | Starting dependencies..
plausible_1            | Starting repos..
```

Here is the content of compose.yml:

```yml
services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    ports:
       - 8000:8000
    image: ghcr.io/plausible/community-edition:v2.1.4
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      # required: https://github.com/plausible/community-edition/wiki/configuration#required
      - BASE_URL=${BASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      # optional: https://github.com/plausible/community-edition/wiki/configuration#optional
      # registration: https://github.com/plausible/community-edition/wiki/configuration#registration
      - TOTP_VAULT_KEY
      - DISABLE_REGISTRATION
      - ENABLE_EMAIL_VERIFICATION
      # web: https://github.com/plausible/community-edition/wiki/configuration#web
      - HTTP_PORT
      - HTTPS_PORT
      # databases: https://github.com/plausible/community-edition/wiki/configuration#database
      - DATABASE_URL
      - CLICKHOUSE_DATABASE_URL
      # Google: https://github.com/plausible/community-edition/wiki/configuration#google
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      # geolocation: https://github.com/plausible/community-edition/wiki/configuration#ip-geolocation
      - IP_GEOLOCATION_DB
      - GEONAMES_SOURCE_FILE
      - MAXMIND_LICENSE_KEY
      - MAXMIND_EDITION
      # email: https://github.com/plausible/community-edition/wiki/configuration#email
      - MAILER_ADAPTER
      - MAILER_EMAIL
      - MAILER_NAME
      - SMTP_HOST_ADDR
      - SMTP_HOST_PORT
      - SMTP_USER_NAME
      - SMTP_USER_PWD
      - SMTP_HOST_SSL_ENABLED
      - POSTMARK_API_KEY
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MAILGUN_BASE_URI
      - MANDRILL_API_KEY
      - SENDGRID_API_KEY

volumes:
  db-data:
  event-data:
  event-logs:
  plausible-data:
```

I'm sure I did something wrong. Any idea?
