### ISSUE TITLE
Plausible crashes and ClickHouse raises an exception

### ISSUE THREAD

**Issue by zkvvoob** [plausible/hosting#206]
Hello,

I'm trying to set up Plausible CE 2.1.4 using the following docker-compose file

```
services:
  plausible_db:
    image: postgres:16-alpine
    container_name: plausible_db
    restart: unless-stopped
    volumes:
      - /mnt/apps/data/plausible/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    container_name: plausible_events
    restart: unless-stopped
    volumes:
      - /mnt/apps/data/plausible/event-data:/var/lib/clickhouse
      - /mnt/apps/data/plausible/event-logs:/var/log/clickhouse-server
      - /mnt/apps/data/plausible/clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      - /mnt/apps/data/plausible/clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      - /mnt/apps/data/plausible/clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.4
    container_name: plausible
    restart: unless-stopped
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - /mnt/apps/data/plausible/plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    env_file:
      - stack.env
```

and **stack.env**

```
BASE_URL=https://plausible.mydomain.com
HTTP_PORT=8090 # the goal is to run it behind a reverse proxy
SECRET_KEY_BASE=<rand 64>
MAILER_EMAIL=noreply@mydomain.com
MAILER_NAME=Plausible
SMTP_HOST_ADDR=mail.mydomain.com
SMTP_HOST_PORT=587
SMTP_USER_NAME=noreply@mydomain.com
SMTP_USER_PWD=<long secure password>
SMTP_HOST_SSL_ENABLED=true
TMPDIR=/var/lib/plausible/tmp
TOTP_VAULT_KEY=<rand 32>
DISABLE_REGISTRATION=invite_only
```

This is a fresh install, with no previous information in the root mount.

**Plausible's Docker logs** show this:

```
Runtime terminating during boot (terminating)
Crash dump is being written to: erl_crash.dump...Loading plausible..
            (kernel 10.0) application_master.erl:295: :application_master.start_it_old/4
            (tzdata 1.1.2) lib/tzdata/tzdata_app.ex:13: Tzdata.App.start/2
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, Tzdata.EtsHolder, {%File.Error{reason: :enoent, path: "/var/lib/plausible/tzdata_data/release_ets", action: "list directory"}, [{File, :ls!, 1, [file: ~c"lib/file.ex", line: 1700]}, {Tzdata.EtsHolder, :release_files_for_dir, 1, [file: ~c"lib/tzdata/ets_holder.ex", line: 127]}, {Tzdata.EtsHolder, :make_sure_a_release_is_on_file, 0, [file: ~c"lib/tzdata/ets_holder.ex", line: 90]}, {Tzdata.EtsHolder, :init, 1, [file: ~c"lib/tzdata/ets_holder.ex", line: 16]}, {:gen_server, :init_it, 2, [file: ~c"gen_server.erl", line: 2057]}, {:gen_server, :init_it, 6, [file: ~c"gen_server.erl", line: 2012]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 329]}]}}}}
    ** (EXIT) an exception was raised:
16:28:27.804 [notice] Application tzdata exited: exited in: Tzdata.App.start(:normal, [])
```

**Clickhouse**

```
ClickHouse Database directory appears to contain a database; Skipping initialization
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/ipv4-only.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/logs.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/low-resources.xml'.
Logging warning to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
2025.01.16 14:26:36.513692 [ 1 ] {} <Warning> Context: Linux is not using a fast clock source. Performance can be degraded. Check /sys/devices/system/clocksource/clocksource0/current_clocksource
2025.01.16 14:26:36.515332 [ 1 ] {} <Warning> Context: Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled
2025.01.16 14:26:37.049213 [ 1 ] {} <Error> Application: Disabling cgroup memory observer because of an error during initialization: Code: 107. DB::Exception: Cannot find cgroups v1 or v2 current memory file. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
1. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x00000000076614c3
2. DB::CgroupsMemoryUsageObserver::CgroupsMemoryUsageObserver(std::chrono::duration<long long, std::ratio<1l, 1l>>) @ 0x000000000cce452e
3. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000cd562bd
4. Poco::Util::Application::run() @ 0x0000000014ca8606
5. DB::Server::run() @ 0x000000000cd46671
6. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000014cb14b9
7. mainEntryClickHouseServer(int, char**) @ 0x000000000cd4246a
8. main @ 0x0000000007651578
9. ? @ 0x00007f1582b75083
10. _start @ 0x0000000005dee46e
 (version 24.3.3.102 (official build))
 ```

Docker version 24.0.7, build afdd53b
Debian GNU/Linux 12 (bookworm)

Any idea what to do here, please?
