### ISSUE TITLE
How to migrate?

### ISSUE THREAD

**Issue by gltched-usr** [plausible/hosting#207]
Hello, 
I'm currently running the "old" version of plausible. How can I migrate to the community edition without loosing data (analytics, settings, users, sites etc.)?

This is my current `docker-compose.yml` file:
```yml
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
    environment:
      - MAILER_EMAIL=analytics@mydomian.com
      - MAILER_NAME=Analytic
      - SMTP_HOST_ADDR=mailserer.mydomian.com
      - SMTP_HOST_PORT=587
      - SMTP_USER_NAME=mail@mydomian.com
      - SMTP_USER_PWD=MyPassword
      - SMTP_HOST_SSL_ENABLED=false
      - SMTP_RETRIES=5
    networks:
      - plausible

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - plausible

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - plausible

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    hostname: plausible
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 7813:8000
    env_file:
      - plausible-conf.env
    networks:
      - plausible
      - npm-network


networks:
  npm-network:
    external: true
  plausible:
    driver: bridge

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
  event-logs:
  plausible-data:

```
