### ISSUE TITLE
The email address `plausible@localhost` is invalid.

### ISSUE THREAD

**Issue by spawnfur** [plausible/hosting#210]
when i try to add a website and there are no other websites on the account, i get this error:
```
plausible          | 20:58:19.417 [error] #PID<0.4803.0> running PlausibleWeb.Endpoint (connection #PID<0.4801.0>, stream id 2) terminated
plausible          | Server: localhost:3008 (http)
plausible          | Request: POST /sites?flow=provisioning
plausible          | ** (exit) an exception was raised:
plausible          |     ** (ArgumentError) The email address `plausible@localhost` is invalid.
plausible          | 
plausible          |         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:134: Mail.Renderers.RFC2822.validate_address/1
plausible          |         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:141: Mail.Renderers.RFC2822.render_address/1
plausible          |         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:97: Mail.Renderers.RFC2822.render_header/2
plausible          |         (elixir 1.17.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
plausible          |         (elixir 1.17.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
plausible          |         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:174: Mail.Renderers.RFC2822.render_headers/2
plausible          |         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:56: Mail.Renderers.RFC2822.render_part/2
plausible          |         (bamboo_mua 0.2.2) lib/bamboo_mua.ex:57: Bamboo.Mua.deliver/2
```

my env variables are:
```yaml
BASE_URL: http://localhost:3008
SECRET_KEY_BASE: redacted
DATABASE_URL: postgres://postgres:postgres@plausible_db:5432/plausible
CLICKHOUSE_DATABASE_URL: http://plausible_events:8123/plausible
```
