### ISSUE TITLE
Exception: Cannot find cgroups v1 or v2 current memory file. (FILE_DOESNT_EXIST)

### ISSUE THREAD

**Issue by hyperdefined** [plausible/hosting#230]
Getting this error on launch randomly. I restarted my container and now this happens below. I've looked at the other issues with this error but neither fixed it for me.

```
plausible_events_db  | ClickHouse Database directory appears to contain a database; Skipping initialization
plausible_events_db  | Processing configuration file '/etc/clickhouse-server/config.xml'.
plausible_events_db  | Merging configuration file '/etc/clickhouse-server/config.d/clickhouse-backups.xml'.
plausible_events_db  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
plausible_events_db  | Merging configuration file '/etc/clickhouse-server/config.d/ipv4-only.xml'.
plausible_events_db  | Merging configuration file '/etc/clickhouse-server/config.d/logs.xml'.
plausible_events_db  | Merging configuration file '/etc/clickhouse-server/config.d/low-resources.xml'.
plausible_events_db  | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
plausible_events_db  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
plausible_events_db  | 2025.04.02 22:13:22.446826 [ 1 ] {} <Warning> Context: Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled
plausible_events_db  | 2025.04.02 22:13:22.447208 [ 1 ] {} <Warning> Context: Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.
plausible_events_db  | 2025.04.02 22:13:22.594198 [ 1 ] {} <Error> Application: Disabling cgroup memory observer because of an error during initialization: Code: 107. DB::Exception: Cannot find cgroups v1 or v2 current memory file. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
plausible_events_db  | 
plausible_events_db  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible_events_db  | 1. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x00000000076614c3
plausible_events_db  | 2. DB::CgroupsMemoryUsageObserver::CgroupsMemoryUsageObserver(std::chrono::duration<long long, std::ratio<1l, 1l>>) @ 0x000000000cce452e
plausible_events_db  | 3. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000cd562bd
plausible_events_db  | 4. Poco::Util::Application::run() @ 0x0000000014ca8606
plausible_events_db  | 5. DB::Server::run() @ 0x000000000cd46671
plausible_events_db  | 6. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000014cb14b9
plausible_events_db  | 7. mainEntryClickHouseServer(int, char**) @ 0x000000000cd4246a
plausible_events_db  | 8. main @ 0x0000000007651578
plausible_events_db  | 9. ? @ 0x00007f67a917c083
plausible_events_db  | 10. _start @ 0x0000000005dee46e
plausible_events_db  |  (version 24.3.3.102 (official build))
plausible exited with code 0
plausible            | Loading plausible..
plausible            | Starting dependencies..
plausible            | Starting repos..
plausible            | Plausible.Repo database already exists
plausible            | Plausible.IngestRepo database already exists
plausible            | Creation of Db successful!
plausible            | Loading plausible..
plausible            | Starting dependencies..
plausible            | Starting repos..
```

Here is my `docker-compose.yml`:
```yaml
services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    container_name: plausible_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      start_period: 1m
  plausible_events_db:
    container_name: plausible_events_db
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
      - /backup/clickhouse:/backups
      - ./clickhouse/clickhouse-backups.xml:/etc/clickhouse-server/config.d/clickhouse-backups.xml:ro
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      - ./clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1
      start_period: 1m
  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.4
    restart: always
    container_name: plausible
    env_file: .env
    ports:
      - 127.0.0.1:3028:3028
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate &&
      /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - ./plausible:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
networks: {}
```
