### ISSUE TITLE
Looking for upgrade info from non-CE edition v2.0.0 to current CE edition

### ISSUE THREAD

**Issue by MagnusThome** [plausible/hosting#238]
I installed plausible in 2022. I think I'm currently on v2.0.0 but am not entirely sure since I can't find a version number other than the pulled docker file in the docker-compose file. The installation is in a directory called hosting which was default using the install scripts at the time AFAIK. I want to keep the logged stats of course and have been searching for info on how to upgrade correctly, the docker-compose.yml for example looks VERY different between the one I installed some years ago and the latest here on github. 

Is there any upgrade instructions for really old non CE to current CE-edition to be found somewhere? 

cat hosting/docker-compose.yml

```
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 80:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

```
