### ISSUE TITLE
Login not working – no response after submission (with Nginx Proxy Manager)

### ISSUE THREAD

**Issue by stormyark** [plausible/hosting#242]
I’ve installed the Plausible Community Edition v3.0.1 using Docker Compose. It runs behind [Nginx Proxy Manager](https://nginxproxymanager.com/) with a valid SSL certificate and a working reverse proxy setup. The application loads correctly, but when attempting to log in, nothing happens — no error, no redirection, no message.

Expected behavior:
Clicking the "Login" button should log me in and redirect to the dashboard.

Actual behavior:
After clicking "Login", the page remains unchanged. There are no errors in the browser console, and no suspicious requests or failures are visible in the network tab.

My setup:

Plausible Image: `ghcr.io/plausible/community-edition:v3.0.1`

Reverse Proxy: Nginx Proxy Manager with SSL

BASE_URL: set to https://plausible.stormyark.de

Docker Compose snippet: (see below)

```yml
services:
  plausible_db:
    image: postgres:16-alpine
    container_name: plausible_db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m
    networks:
      - intranet

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    container_name: plausible_events_db
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      # This makes ClickHouse consume less resources, which is useful for small setups.
      # https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram
      - ./clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m
    networks:
      - intranet

  plausible:
    image: ghcr.io/plausible/community-edition:v3.0.1
    container_name: plausible
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ports:
      - 8000:${HTTP_PORT}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      # required: https://github.com/plausible/community-edition/wiki/configuration#required
      - BASE_URL=${BASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      # optional: https://github.com/plausible/community-edition/wiki/configuration#optional
      # registration: https://github.com/plausible/community-edition/wiki/configuration#registration
      - TOTP_VAULT_KEY
      - DISABLE_REGISTRATION
      - ENABLE_EMAIL_VERIFICATION
      # web: https://github.com/plausible/community-edition/wiki/configuration#web
      - HTTP_PORT
      - HTTPS_PORT
      # databases: https://github.com/plausible/community-edition/wiki/configuration#database
      - DATABASE_URL
      - CLICKHOUSE_DATABASE_URL
      # Google: https://github.com/plausible/community-edition/wiki/configuration#google
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      # geolocation: https://github.com/plausible/community-edition/wiki/configuration#ip-geolocation
      - IP_GEOLOCATION_DB
      - GEONAMES_SOURCE_FILE
      - MAXMIND_LICENSE_KEY
      - MAXMIND_EDITION
      # email: https://github.com/plausible/community-edition/wiki/configuration#email
      - MAILER_ADAPTER
      - MAILER_EMAIL
      - MAILER_NAME
      - SMTP_HOST_ADDR
      - SMTP_HOST_PORT
      - SMTP_USER_NAME
      - SMTP_USER_PWD
      - SMTP_HOST_SSL_ENABLED
      - POSTMARK_API_KEY
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MAILGUN_BASE_URI
      - MANDRILL_API_KEY
      - SENDGRID_API_KEY
    networks:
      - intranet

volumes:
  db-data:
  event-data:
  event-logs:
  plausible-data:

networks:
  intranet:
    external: true
```
What I’ve tried:

- Confirmed BASE_URL is correct
- Cleared cookies and cache
- Reissued SSL certificate
- Tested in private/incognito mode
- Tried multiple browsers

Question:
Could Plausible require specific headers or forwarding rules when used behind a reverse proxy? Are there any known limitations when using Nginx Proxy Manager?

Thanks in advance for your help!

**Comment by KarelWintersky** [comment]
Nginx proxy manager is a completely useless add-on over nginx. I recommend abandoning it at the first opportunity and using "pure" nginx.

It works well only for very simple, primitive cases, but setting up any complex project with forwarding environment variables or headers turns into shamanism with unpredictable results.

If you are interested in my config for nginx (I have Plausible in a LXC container on Proxmox BEHIND a regular nginx proxy) - contact me (here)

**Comment by xtzws** [comment]
I don't use nginx but when I had this same problem, I ended up needing to also proxy all websocket requests to the Plausible server.

**Comment by KarelWintersky** [comment]
Change `composer-override` to 
```
services:
  plausible:
    ports:
      - 8000:8000
```

proxy vhost (certbot not included)
```
server {
    listen 80;
    set $plausible_host 192.168.1.99;

    server_name my.domain;

    error_log   /var/log/nginx/plausible.error.log;
    access_log  /var/log/nginx/plausible.access.log main;


    location / {
        proxy_pass http://$plausible_host:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;

        proxy_intercept_errors on;
        error_page 500 502 503 504 =503 /empty.gif;
    }

    location /live/websocket {
        proxy_pass http://$plausible_host:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location = /empty.gif {
        empty_gif;
        expires 0;
        add_header Cache-Control "no-cache";
    }

    location favicon.* { access_log  off; log_not_found off; }
}

```
