### ISSUE TITLE
Email not working and no way of debugging

### ISSUE THREAD

**Issue by Crocmagnon** [plausible/hosting#30]
I'm trying to setup plausible to send weekly and monthly reports. I added the relevant variables but I don't receive the emails.

I couldn't find any way to send an email immediately, and I don't really want to wait 1 week between retries 😊 

Here's my conf:
```env
MAILER_EMAIL=plausible@mg.augendre.info
SMTP_HOST_ADDR=smtp.mailgun.org
SMTP_HOST_PORT=465
SMTP_USER_NAME=plausible@mg.augendre.info
SMTP_USER_PWD=supersecurepassword
SMTP_HOST_SSL_ENABLED=true
SMTP_RETRIES=2
```

**Comment by kevinvalk** [comment]
I faced the same issue. You can run docker without `--detach` and when doing a password reset or registering a new user you get an error:
```plain
[warn] Failed to send Sentry event.Cannot send Sentry event because of invalid DSN
```
Which I think is weird. It happens with `SMTP_HOST_ADDR` set to `localhost`, `127.0.0.1` and the special `host.docker.internal`  (see blow for requirement) and I guess is a bug.

Workaround that I used is letting the mail service relay it again (NOTE: It does not handle IPv6 well in my IPv6 less docker host)
```yaml
  mail:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp.mailgun.org
      RELAY_PORT: 465
      RELAY_USERNAME: alice@example.com
      RELAY_PASSWORD: secretpassword
```
See: https://hub.docker.com/r/bytemark/smtp/

Add this to your service if you want to have the host addressable via `host.docker.internal`
```yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
